In [1]:
#교차 검증을 그림으로 설명하기	Ch.05(05-3) 앙상블 모델 손코딩 코랩 화면 인증하기
import pandas as pd
wine = pd.read_csv('hg-mldl-master/wine.csv')
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [2]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

print(data[:10])
print(target[:10])


[[ 9.4   1.9   3.51]
 [ 9.8   2.6   3.2 ]
 [ 9.8   2.3   3.26]
 [ 9.8   1.9   3.16]
 [ 9.4   1.9   3.51]
 [ 9.4   1.8   3.51]
 [ 9.4   1.6   3.3 ]
 [10.    1.2   3.39]
 [ 9.5   2.    3.36]
 [10.5   6.1   3.35]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
from sklearn.model_selection import train_test_split

trainInput, testIntput, trainTarget, testTarget = train_test_split(data, target, test_size=0.2, random_state=42)
print(trainInput[:5])
print(trainTarget[:5])

[[10.5   7.7   3.19]
 [12.4   2.1   3.26]
 [11.8   2.1   3.41]
 [11.7   1.2   3.37]
 [ 9.3  15.4   3.11]]
[1. 0. 0. 1. 1.]


In [ ]:
sub_input, val_input, sub_target, val_target = train_test_split(trainInput, trainTarget, test)