In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('hg-mldl-master/wine.csv')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()
trainInput, testIntput, trainTarget, testTarget = train_test_split(data, target, test_size=0.2, random_state=42)
print(trainInput[:5])
print(trainTarget[:5])

[[10.5   7.7   3.19]
 [12.4   2.1   3.26]
 [11.8   2.1   3.41]
 [11.7   1.2   3.37]
 [ 9.3  15.4   3.11]]
[1. 0. 0. 1. 1.]


In [6]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs= -1, random_state=42)
scores = cross_validate(rf, trainInput, trainTarget, return_train_score=True, n_jobs=-1)


{'fit_time': array([0.29799843, 0.31499863, 0.40499735, 0.30399919, 0.26299977]),
 'score_time': array([0.10899997, 0.12600112, 0.10899878, 0.10999942, 0.112149  ]),
 'test_score': array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926]),
 'train_score': array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])}

In [8]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores


0.9973541965122431
0.8905151032797809


{'fit_time': array([0.29799843, 0.31499863, 0.40499735, 0.30399919, 0.26299977]),
 'score_time': array([0.10899997, 0.12600112, 0.10899878, 0.10999942, 0.112149  ]),
 'test_score': array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926]),
 'train_score': array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])}

In [9]:
rf.fit(trainInput, trainTarget)
rf.feature_importances_

array([0.23167441, 0.50039841, 0.26792718])

In [13]:
rf = RandomForestClassifier(oob_score=False, n_jobs=-1, random_state=42)
rf.fit(trainInput, trainTarget)
# print(rf.oob_score_)
print(rf.oob_score)

False


In [11]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(trainInput, trainTarget)
print(rf.oob_score_)
print(rf.oob_score)

0.8934000384837406
True


In [14]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, trainInput, trainTarget, return_train_score=True, n_jobs=-1)


print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores

#엑스트라 무작위성이 큼, 훈련양이 많음 속도가 빠름 
#포레스트

0.9974503966084433
0.8887848893166506


{'fit_time': array([0.31000042, 0.3750155 , 0.29099917, 0.3900075 , 0.28003788]),
 'score_time': array([0.11801624, 0.11499643, 0.13901281, 0.11200309, 0.11004639]),
 'test_score': array([0.88365385, 0.87884615, 0.90375361, 0.88835419, 0.88931665]),
 'train_score': array([0.9971133 , 0.99663219, 0.998076  , 0.997595  , 0.9978355 ])}

In [15]:
et.fit(trainInput, trainTarget)
et.feature_importances_

array([0.20183568, 0.52242907, 0.27573525])

In [16]:
#그레디언트 부스팅->경사 하강법

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
    scores = cross_validate(gb, trainInput, trainTarget, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores


0.8881086892152563
0.8720430147331015


{'fit_time': array([0.24899769, 0.2489996 , 0.25899911, 0.25999975, 0.23799968]),
 'score_time': array([0.00199866, 0.00199938, 0.00299931, 0.00300193, 0.00199938]),
 'test_score': array([0.86634615, 0.87019231, 0.89412897, 0.86044273, 0.86910491]),
 'train_score': array([0.89006495, 0.88958383, 0.88239538, 0.89249639, 0.88600289])}

In [17]:
#n_estimators 결정트리
#n_estimators
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, trainInput, trainTarget, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores

0.9464595437171814
0.8780082549788999


{'fit_time': array([1.24199629, 1.24999738, 1.26199389, 1.27299905, 1.2009995 ]),
 'score_time': array([0.01000166, 0.00699949, 0.01300097, 0.0079999 , 0.00699949]),
 'test_score': array([0.875     , 0.87211538, 0.89701636, 0.8719923 , 0.87391723]),
 'train_score': array([0.9494828 , 0.94443108, 0.94468494, 0.94324194, 0.95045695])}

In [19]:
gb.fit(trainInput, trainTarget)
gb.feature_importances_

array([0.15872278, 0.68011572, 0.16116151])

In [20]:
#히그토그램 기반
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, trainInput, trainTarget, return_train_score=True)
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores


0.9321723946453317
0.8801241948619236


{'fit_time': array([0.35199976, 0.34300017, 0.41300011, 0.34800029, 0.34400034]),
 'score_time': array([0.00599909, 0.00500011, 0.00599957, 0.0059998 , 0.0059998 ]),
 'test_score': array([0.87115385, 0.88365385, 0.90279115, 0.86621752, 0.87680462]),
 'train_score': array([0.93192206, 0.93216262, 0.92857143, 0.93265993, 0.93554594])}

In [24]:
from sklearn.inspection import permutation_importance

hgb.fit(trainInput, trainTarget)
result = permutation_importance(hgb, trainInput, trainTarget, n_repeats=10, random_state=42, n_jobs=-1)

result

{'importances_mean': array([0.08876275, 0.23438522, 0.08027708]),
 'importances_std': array([0.00382333, 0.00401363, 0.00477012]),
 'importances': array([[0.08793535, 0.08350972, 0.08908986, 0.08312488, 0.09274581,
         0.08755051, 0.08601116, 0.09601693, 0.09082163, 0.09082163],
        [0.22782374, 0.23590533, 0.23936887, 0.23436598, 0.23725226,
         0.23436598, 0.23359631, 0.23398114, 0.23994612, 0.22724649],
        [0.08581874, 0.08601116, 0.08062344, 0.07504329, 0.08427939,
         0.07792957, 0.07234943, 0.07465846, 0.08139311, 0.08466423]])}

In [25]:
result = permutation_importance(hgb, testIntput, testTarget, n_repeats=10, random_state=42, n_jobs=-1)
result

{'importances_mean': array([0.05969231, 0.20238462, 0.049     ]),
 'importances_std': array([0.004     , 0.007938  , 0.00453846]),
 'importances': array([[0.06230769, 0.05769231, 0.05538462, 0.05538462, 0.06076923,
         0.06076923, 0.06846154, 0.06230769, 0.05461538, 0.05923077],
        [0.20076923, 0.2       , 0.21153846, 0.20076923, 0.20307692,
         0.18923077, 0.19615385, 0.19461538, 0.21384615, 0.21384615],
        [0.05692308, 0.04692308, 0.05076923, 0.04769231, 0.04692308,
         0.05      , 0.04384615, 0.04692308, 0.04307692, 0.05692308]])}

In [26]:
hgb.score(testIntput, testTarget)

0.8723076923076923

In [32]:
#C:\Users\lotco\.conda\envs\tf36\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
#  warnings.warn(label_encoder_deprecation_msg, UserWarning)
#C:\Users\lotco\.conda\envs\tf36\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
#  warnings.warn(label_encoder_deprecation_msg, UserWarning)
#use_label_encoder=False, eval_metric='mlogloss'
#https://stackoverflow.com/questions/66097701/how-can-i-fix-this-warning-in-xgboost


from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42, use_label_encoder=False, eval_metric='mlogloss' )
scores = cross_validate(xgb, trainInput, trainTarget, return_train_score=True)
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))
scores


0.9555033709953124
0.8799326275264677


{'fit_time': array([0.07899785, 0.06800079, 0.06800079, 0.0679996 , 0.06899905]),
 'score_time': array([0.00300002, 0.00299978, 0.00200009, 0.00200009, 0.00200081]),
 'test_score': array([0.8625    , 0.8875    , 0.89797883, 0.87969201, 0.8719923 ]),
 'train_score': array([0.95814289, 0.9569401 , 0.95526696, 0.95286195, 0.95430495])}

In [33]:
results = permutation_importance(hgb, testIntput, testTarget, n_repeats=10, random_state=42, n_jobs=-1)
result

{'importances_mean': array([0.05969231, 0.20238462, 0.049     ]),
 'importances_std': array([0.004     , 0.007938  , 0.00453846]),
 'importances': array([[0.06230769, 0.05769231, 0.05538462, 0.05538462, 0.06076923,
         0.06076923, 0.06846154, 0.06230769, 0.05461538, 0.05923077],
        [0.20076923, 0.2       , 0.21153846, 0.20076923, 0.20307692,
         0.18923077, 0.19615385, 0.19461538, 0.21384615, 0.21384615],
        [0.05692308, 0.04692308, 0.05076923, 0.04769231, 0.04692308,
         0.05      , 0.04384615, 0.04692308, 0.04307692, 0.05692308]])}

In [34]:
hgb.score(testIntput, testTarget)

0.8723076923076923

In [42]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier(random_state=42)
scores = cross_validate(lgb, trainInput, trainTarget, return_train_score=True, n_jobs=-1)